/* =============================================
   export.js — ZIP Export + Config Import/Export
   ============================================= */
async function downloadZIP() {
  Utils.showLoading(I18N.t('loading.zipping'));
  try {
    const data = FormState.getData();
    const theme = getTheme(FormState.data.theme || 3);
    const portfolioHtml = theme.render(data);
    const zip = new JSZip();

    // Add index.html
    zip.file('index.html', portfolioHtml);

    // Add minimal CSS (inline styles already in templates, but add a minimal reset)
    zip.file('style.css', `/* Portfolio styles are inline in index.html */\n/* This file is provided for custom overrides */\nbody { font-family: system-ui, sans-serif; }\n`);

    // Add a README
    zip.file('README.md', `# ${data.name} — Portfolio\n\nGenerated by [Universal Portfolio Generator](https://github.com/${data.slug}/portfolio-generator)\n\n### Deploy\n1. Push to GitHub Pages\n2. Or upload to Netlify/Vercel\n`);

    // Add CNAME placeholder
    zip.file('CNAME', '');

    // Add .nojekyll for GitHub Pages
    zip.file('.nojekyll', '');

    // Generate zip
    const blob = await zip.generateAsync({ type: 'blob' });
    saveAs(blob, `${data.slug || 'portfolio'}-portfolio.zip`);

    Utils.hideLoading();
    Utils.showToast(I18N.t('success.zipped'), 'success');
    showDownloadTip();
  } catch (e) {
    Utils.hideLoading();
    console.error('ZIP error:', e);
    Utils.showToast('Failed to create ZIP: ' + e.message, 'error');
  }
}

function exportConfig() {
  const data = FormState.data;
  const exportData = {
    version: '1.0',
    generator: 'Universal Portfolio Generator',
    generated: new Date().toISOString(),
    portfolio: {
      name: data.name,
      bio: data.bio,
      role: data.role,
      email: data.email,
      location: data.location,
      photo: data.photo,
      socials: data.socials,
      skills: data.skills,
      projects: data.projects,
      theme: data.theme,
      metrics: data.metrics
    }
  };
  Utils.downloadJSON(exportData, 'portfolio-config.json');
  Utils.showToast(I18N.t('success.configSaved'), 'success');
}

function importConfig() {
  const input = document.createElement('input');
  input.type = 'file';
  input.accept = '.json';
  input.onchange = async (e) => {
    if (!e.target.files?.[0]) return;
    try {
      const json = await Utils.loadJSONFile(e.target.files[0]);
      if (json.portfolio) {
        Object.assign(FormState.data, json.portfolio);
        FormState.renderStep(FormState.currentStep);
        triggerPreview();
        Utils.showToast(I18N.t('success.configLoaded'), 'success');
      }
    } catch (err) {
      Utils.showToast('Invalid config file', 'error');
    }
  };
  input.click();
}

function showDownloadTip() {
  const isAr = I18N.current === 'ar';
  const tips = isAr ? [
    '📖 افتح ملف index.html وابحث عن الأقسام التي تعجبك',
    '🛠️ حاول تغيير الألوان والخطوط بنفسك — التجربة أفضل معلم',
    '🧠 أضف مهاراتك ومشاريعك الحقيقية — هذا موقعك الشخصي',
    '🚀 انشر الموقع على GitHub Pages مجاناً',
    '📱 اختبر الموقع على جوالك — تأكد أن كل شيء يظهر بشكل صحيح',
    '🎨 غيّر الثيم وجرب تنسيقات مختلفة',
    '💡 اربط حساب GitHub عشان تجيب مشاريعك تلقائياً'
  ] : [
    '📖 Open index.html and explore sections that catch your eye',
    '🛠️ Try changing colors and fonts yourself — experimentation is the best teacher',
    '🧠 Add your real skills and projects — this is YOUR portfolio',
    '🚀 Deploy to GitHub Pages for free hosting',
    '📱 Test on mobile — make sure everything displays correctly',
    '🎨 Switch themes and try different layouts',
    '💡 Connect GitHub to auto-import your repositories'
  ];
  const tip = tips[Math.floor(Math.random() * tips.length)];
  document.getElementById('tip-modal-title').textContent = isAr ? '💡 نصيحة' : '💡 Tip';
  document.getElementById('tip-modal-text').textContent = tip;
  document.getElementById('tip-modal').classList.remove('hidden');
  document.getElementById('tip-modal').style.display = 'flex';
}
