/* =============================================
   github.js — GitHub Auto-Deploy via @octokit/rest
   ============================================= */
async function deployToGitHub() {
  const pat = document.getElementById('pat-input').value.trim();
  if (!pat) {
    document.getElementById('pat-input')?.focus();
    Utils.showToast(I18N.t('error.patRequired'), 'error');
    return;
  }

  // Get user's repo name choice
  const customRepo = document.getElementById('repo-name-input')?.value?.trim() || '';
  const username = await getLoginFromPat(pat).catch(() => null);
  if (!username) {
    Utils.showToast('Invalid GitHub token. Check and try again.', 'error');
    return;
  }

  // Determine repo name — priority: custom > {user}.github.io > portfolio
  const repoName = customRepo || `${username}.github.io`;

  Utils.showLoading(`Deploying to ${username}/${repoName} ...`);

  try {
    const octokit = new Octokit({ auth: pat });
    const data = FormState.getData();
    const theme = getTheme(FormState.data.theme || 3);
    const portfolioHtml = theme.render(data);
    const domain = FormState.data.customDomain?.trim();

    // Check if repo exists
    let repoExists = false;
    try {
      await octokit.repos.get({ owner: username, repo: repoName });
      repoExists = true;
    } catch (e) {
      repoExists = false;
    }

    if (!repoExists) {
      Utils.showLoading(`Creating repo ${repoName} ...`);
      await octokit.repos.createForAuthenticatedUser({
        name: repoName,
        description: 'My portfolio — generated by Universal Portfolio Generator',
        auto_init: true
      });
      await new Promise(r => setTimeout(r, 3000));
    }

    // Get the default branch
    const { data: repo } = await octokit.repos.get({ owner: username, repo: repoName });
    const branch = repo.default_branch || 'main';

    // Get current commit SHA
    let latestCommitSha;
    try {
      const { data: ref } = await octokit.git.getRef({
        owner: username, repo: repoName, ref: `heads/${branch}`
      });
      latestCommitSha = ref.object.sha;
    } catch (e) {
      latestCommitSha = null;
    }

    // Build file tree
    Utils.showLoading(`Committing portfolio files ...`);
    const files = [
      { path: 'index.html', content: portfolioHtml },
      { path: '.nojekyll', content: '' }
    ];
    if (domain) {
      files.push({ path: 'CNAME', content: domain });
    }

    // Create blobs
    const treeEntries = [];
    for (const file of files) {
      const encoded = btoa(unescape(encodeURIComponent(file.content)));
      const { data: blob } = await octokit.git.createBlob({
        owner: username, repo: repoName,
        content: encoded, encoding: 'base64'
      });
      treeEntries.push({
        path: file.path, mode: '100644', type: 'blob', sha: blob.sha
      });
    }

    const message = '🚀 Portfolio generated by Universal Portfolio Generator';
    let latestTreeSha;

    if (latestCommitSha) {
      const { data: commit } = await octokit.git.getCommit({
        owner: username, repo: repoName, commit_sha: latestCommitSha
      });
      latestTreeSha = commit.tree.sha;
    }

    const { data: tree } = await octokit.git.createTree({
      owner: username, repo: repoName,
      base_tree: latestTreeSha || undefined,
      tree: treeEntries
    });

    if (latestCommitSha) {
      const { data: newCommit } = await octokit.git.createCommit({
        owner: username, repo: repoName,
        message, tree: tree.sha, parents: [latestCommitSha]
      });
      await octokit.git.updateRef({
        owner: username, repo: repoName,
        ref: `heads/${branch}`, sha: newCommit.sha
      });
    } else {
      const { data: newCommit } = await octokit.git.createCommit({
        owner: username, repo: repoName, message, tree: tree.sha, parents: []
      });
      await octokit.git.createRef({
        owner: username, repo: repoName,
        ref: `refs/heads/${branch}`, sha: newCommit.sha
      });
    }

    // Enable GitHub Pages
    Utils.showLoading(`Enabling GitHub Pages ...`);
    try {
      await octokit.repos.enablePages({
        owner: username, repo: repoName,
        source: { branch: branch, path: '/' }
      });
    } catch (e) {
      console.warn('Pages enable warn:', e);
    }

    const liveUrl = domain
      ? `https://${domain}`
      : repoName.includes('.github.io')
        ? `https://${repoName}/`
        : `https://${username}.github.io/${repoName}/`;

    Utils.hideLoading();
    Utils.showToast(`✅ Deployed! ${liveUrl}`, 'success');
    document.getElementById('pat-input').value = '';

    // Show success with link
    const resultDiv = document.getElementById('deploy-result');
    if (resultDiv) {
      resultDiv.innerHTML = `
        <div class="mt-4 p-4 bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 rounded-xl text-center">
          <i class="fas fa-check-circle text-3xl text-green-500 mb-2"></i>
          <p class="font-semibold text-green-700 dark:text-green-300">Deployed Successfully!</p>
          <a href="${liveUrl}" target="_blank" class="text-blue-600 dark:text-blue-400 underline text-sm break-all">${liveUrl}</a>
          <p class="text-xs text-gray-500 mt-1">It may take 1-2 minutes for Pages to build</p>
        </div>
      `;
    }

  } catch (e) {
    Utils.hideLoading();
    console.error('Deploy error:', e);
    Utils.showToast(`❌ Deploy failed: ${e.message}`, 'error');
  }
}

/** Get GitHub username from a PAT by calling the API */
async function getLoginFromPat(pat) {
  const octokit = new Octokit({ auth: pat });
  const { data } = await octokit.users.getAuthenticated();
  return data.login;
}

async function getUserLogin(octokit) {
  const { data } = await octokit.users.getAuthenticated();
  return data.login;
}

// GitHub Auto-Sync: fetch user's top repos
async function syncGitHubRepos() {
  const pat = document.getElementById('pat-input').value.trim();
  if (!pat) {
    Utils.showToast('Enter your PAT first to sync repos', 'error');
    return;
  }
  Utils.showLoading('Fetching your repositories...');
  try {
    const octokit = new Octokit({ auth: pat });
    const { data: repos } = await octokit.repos.listForAuthenticatedUser({
      sort: 'updated', per_page: 12, type: 'owner'
    });
    const topRepos = repos.filter(r => !r.fork).slice(0, 6);
    topRepos.forEach(r => {
      if (!FormState.data.projects.find(p => p.name === r.name)) {
        FormState.data.projects.push({
          name: r.name,
          desc: r.description || 'A repository on GitHub',
          tags: [r.language || 'code'],
          url: r.html_url
        });
      }
    });
    // Update metrics
    FormState.data.metrics = [
      { value: repos.length, label: 'Repositories' },
      { value: repos.reduce((s, r) => s + r.stargazers_count, 0), label: 'Total Stars' },
      { value: repos.filter(r => r.fork).length, label: 'Forks' }
    ];
    Utils.hideLoading();
    Utils.showToast(`Synced ${topRepos.length} repositories!`, 'success');
    FormState.renderStep(FormState.currentStep);
    triggerPreview();
  } catch (e) {
    Utils.hideLoading();
    Utils.showToast('Failed to sync repos: ' + e.message, 'error');
  }
}

// Custom Domain Wizard
function generateCNAME() {
  const domain = FormState.data.customDomain.trim();
  if (!domain) {
    Utils.showToast('Enter a custom domain first', 'error');
    return;
  }
  // Generate CNAME file content for display/copy
  const content = domain;
  // Copy to clipboard
  navigator.clipboard.writeText(content).then(() => {
    Utils.showToast(`CNAME file: "${domain}" copied to clipboard!`, 'success');
  }).catch(() => {
    Utils.showToast(`CNAME: ${domain}`, 'info');
  });
}
