async function deployToGitHub() {
  const username = document.getElementById('deploy-username')?.value?.trim();
  const pat = document.getElementById('pat-input')?.value?.trim();

  if (!username) {
    document.getElementById('deploy-username')?.focus();
    Utils.showToast(I18N.current === 'ar' ? 'أدخل اسم حساب GitHub' : 'Enter your GitHub username', 'error');
    return;
  }
  if (!pat) {
    document.getElementById('pat-input')?.focus();
    Utils.showToast(I18N.current === 'ar' ? 'أدخل رمز GitHub PAT' : 'Enter your GitHub token', 'error');
    return;
  }

  const repoName = 'portfolio';
  Utils.showLoading(I18N.current === 'ar' ? `جارٍ النشر إلى ${username}/${repoName} ...` : `Deploying to ${username}/${repoName} ...`);

  try {
    const octokit = new Octokit({ auth: pat });

    let repoExists = false;
    try {
      await octokit.repos.get({ owner: username, repo: repoName });
      repoExists = true;
    } catch (_) {
      repoExists = false;
    }

    if (!repoExists) {
      Utils.showLoading(I18N.current === 'ar' ? `إنشاء مستودع ${repoName} ...` : `Creating repo ${repoName} ...`);
      await octokit.repos.createForAuthenticatedUser({
        name: repoName,
        description: 'My portfolio — generated by Universal Portfolio Generator',
        auto_init: true
      });
      await new Promise(r => setTimeout(r, 3000));
    }

    const data = FormState.getData();
    const theme = getTheme(FormState.data.theme || 3);
    const portfolioHtml = theme.render(data);

    const { data: repo } = await octokit.repos.get({ owner: username, repo: repoName });
    const branch = repo.default_branch || 'main';

    let latestCommitSha;
    try {
      const { data: ref } = await octokit.git.getRef({ owner: username, repo: repoName, ref: `heads/${branch}` });
      latestCommitSha = ref.object.sha;
    } catch (_) {
      latestCommitSha = null;
    }

    Utils.showLoading(I18N.current === 'ar' ? 'رفع الملفات ...' : 'Uploading files ...');

    const files = [
      { path: 'index.html', content: portfolioHtml },
      { path: '.nojekyll', content: '' }
    ];

    const treeEntries = [];
    for (const file of files) {
      const encoded = btoa(unescape(encodeURIComponent(file.content)));
      const { data: blob } = await octokit.git.createBlob({
        owner: username, repo: repoName, content: encoded, encoding: 'base64'
      });
      treeEntries.push({ path: file.path, mode: '100644', type: 'blob', sha: blob.sha });
    }

    const message = 'portfolio — generated by Universal Portfolio Generator';
    let latestTreeSha;
    if (latestCommitSha) {
      const { data: commit } = await octokit.git.getCommit({ owner: username, repo: repoName, commit_sha: latestCommitSha });
      latestTreeSha = commit.tree.sha;
    }

    const { data: tree } = await octokit.git.createTree({ owner: username, repo: repoName, base_tree: latestTreeSha || undefined, tree: treeEntries });

    if (latestCommitSha) {
      const { data: newCommit } = await octokit.git.createCommit({ owner: username, repo: repoName, message, tree: tree.sha, parents: [latestCommitSha] });
      await octokit.git.updateRef({ owner: username, repo: repoName, ref: `heads/${branch}`, sha: newCommit.sha });
    } else {
      const { data: newCommit } = await octokit.git.createCommit({ owner: username, repo: repoName, message, tree: tree.sha, parents: [] });
      await octokit.git.createRef({ owner: username, repo: repoName, ref: `refs/heads/${branch}`, sha: newCommit.sha });
    }

    Utils.showLoading(I18N.current === 'ar' ? 'تفعيل GitHub Pages ...' : 'Enabling GitHub Pages ...');
    try {
      await octokit.repos.enablePages({ owner: username, repo: repoName, source: { branch: branch, path: '/' } });
    } catch (_) {}

    const liveUrl = `https://${username}.github.io/${repoName}/`;

    Utils.hideLoading();
    document.getElementById('pat-input').value = '';
    document.getElementById('deploy-username').value = '';

    document.getElementById('deploy-result').innerHTML = `
      <div class="p-4 rounded-xl text-center" style="background:#f0fdf4;border:1px solid #bbf7d0">
        <div class="text-2xl mb-1" style="color:#16a34a">&#10003;</div>
        <p class="font-semibold text-sm" style="color:#166534">Deployed</p>
        <a href="${liveUrl}" target="_blank" class="block text-xs underline mt-1 break-all" style="color:#2563eb">${liveUrl}</a>
        <p class="text-xs mt-1" style="color:#6b7280">Wait 1-2 min for Pages build</p>
      </div>
    `;
  } catch (e) {
    Utils.hideLoading();
    Utils.showToast(I18N.current === 'ar' ? 'فشل النشر: ' + e.message : 'Deploy failed: ' + e.message, 'error');
  }
}
