/* =============================================
   github.js — GitHub Auto-Deploy via @octokit/rest
   ============================================= */
async function deployToGitHub() {
  const pat = document.getElementById('pat-input').value.trim();
  if (!pat) {
    document.getElementById('pat-section').classList.remove('hidden');
    Utils.showToast(I18N.t('error.patRequired'), 'error');
    return;
  }

  Utils.showLoading(I18N.t('loading.deploying'));

  try {
    const octokit = new Octokit({ auth: pat });
    const username = await getUserLogin(octokit);
    const repoName = `${username}.github.io`;
    const data = FormState.getData();
    const theme = getTheme(FormState.data.theme || 3);
    const portfolioHtml = theme.render(data);

    // Check if repo exists
    let repoExists = false;
    try {
      await octokit.repos.get({ owner: username, repo: repoName });
      repoExists = true;
    } catch (e) {
      repoExists = false;
    }

    if (!repoExists) {
      // Create repo
      await octokit.repos.createForAuthenticatedUser({
        name: repoName,
        description: 'My portfolio generated by Universal Portfolio Generator',
        auto_init: true
      });
      // Wait for initial commit
      await new Promise(r => setTimeout(r, 3000));
    }

    // Get the default branch
    const { data: repo } = await octokit.repos.get({ owner: username, repo: repoName });
    const branch = repo.default_branch || 'main';

    // Get current commit SHA
    let latestCommitSha;
    try {
      const { data: ref } = await octokit.git.getRef({
        owner: username, repo: repoName, ref: `heads/${branch}`
      });
      latestCommitSha = ref.object.sha;
    } catch (e) {
      latestCommitSha = null;
    }

    // Create or update index.html
    const content = btoa(unescape(encodeURIComponent(portfolioHtml)));
    const message = 'Update portfolio via Universal Portfolio Generator';

    if (latestCommitSha) {
      // Get the current tree
      const { data: commit } = await octokit.git.getCommit({
        owner: username, repo: repoName, commit_sha: latestCommitSha
      });

      // Create new blob
      const { data: blob } = await octokit.git.createBlob({
        owner: username, repo: repoName,
        content: content, encoding: 'base64'
      });

      // Create new tree
      const { data: tree } = await octokit.git.createTree({
        owner: username, repo: repoName,
        base_tree: commit.tree.sha,
        tree: [{
          path: 'index.html',
          mode: '100644',
          type: 'blob',
          sha: blob.sha
        }]
      });

      // Create new commit
      const { data: newCommit } = await octokit.git.createCommit({
        owner: username, repo: repoName,
        message: message,
        tree: tree.sha,
        parents: [latestCommitSha]
      });

      // Update ref
      await octokit.git.updateRef({
        owner: username, repo: repoName,
        ref: `heads/${branch}`,
        sha: newCommit.sha
      });
    } else {
      // First commit
      const { data: blob } = await octokit.git.createBlob({
        owner: username, repo: repoName,
        content: content, encoding: 'base64'
      });
      const { data: tree } = await octokit.git.createTree({
        owner: username, repo: repoName,
        tree: [{ path: 'index.html', mode: '100644', type: 'blob', sha: blob.sha }]
      });
      const { data: newCommit } = await octokit.git.createCommit({
        owner: username, repo: repoName,
        message: message, tree: tree.sha, parents: []
      });
      await octokit.git.createRef({
        owner: username, repo: repoName,
        ref: `refs/heads/${branch}`,
        sha: newCommit.sha
      });
    }

    // Enable GitHub Pages
    try {
      await octokit.repos.enablePages({
        owner: username, repo: repoName,
        source: { branch: branch, path: '/' }
      });
    } catch (e) {
      // Pages might already be enabled
    }

    Utils.hideLoading();
    Utils.showToast(`${I18N.t('success.deployed')} https://${username}.github.io/`, 'success');
    document.getElementById('pat-input').value = '';

  } catch (e) {
    Utils.hideLoading();
    console.error('Deploy error:', e);
    Utils.showToast(`${I18N.t('error.deployFailed')} ${e.message}`, 'error');
  }
}

async function getUserLogin(octokit) {
  const { data } = await octokit.users.getAuthenticated();
  return data.login;
}

// GitHub Auto-Sync: fetch user's top repos
async function syncGitHubRepos() {
  const pat = document.getElementById('pat-input').value.trim();
  if (!pat) {
    Utils.showToast('Enter your PAT first to sync repos', 'error');
    return;
  }
  Utils.showLoading('Fetching your repositories...');
  try {
    const octokit = new Octokit({ auth: pat });
    const { data: repos } = await octokit.repos.listForAuthenticatedUser({
      sort: 'updated', per_page: 12, type: 'owner'
    });
    const topRepos = repos.filter(r => !r.fork).slice(0, 6);
    topRepos.forEach(r => {
      if (!FormState.data.projects.find(p => p.name === r.name)) {
        FormState.data.projects.push({
          name: r.name,
          desc: r.description || 'A repository on GitHub',
          tags: [r.language || 'code'],
          url: r.html_url
        });
      }
    });
    // Update metrics
    FormState.data.metrics = [
      { value: repos.length, label: 'Repositories' },
      { value: repos.reduce((s, r) => s + r.stargazers_count, 0), label: 'Total Stars' },
      { value: repos.filter(r => r.fork).length, label: 'Forks' }
    ];
    Utils.hideLoading();
    Utils.showToast(`Synced ${topRepos.length} repositories!`, 'success');
    FormState.renderStep(FormState.currentStep);
    triggerPreview();
  } catch (e) {
    Utils.hideLoading();
    Utils.showToast('Failed to sync repos: ' + e.message, 'error');
  }
}

// Custom Domain Wizard
function generateCNAME() {
  const domain = FormState.data.customDomain.trim();
  if (!domain) {
    Utils.showToast('Enter a custom domain first', 'error');
    return;
  }
  // Generate CNAME file content for display/copy
  const content = domain;
  // Copy to clipboard
  navigator.clipboard.writeText(content).then(() => {
    Utils.showToast(`CNAME file: "${domain}" copied to clipboard!`, 'success');
  }).catch(() => {
    Utils.showToast(`CNAME: ${domain}`, 'info');
  });
}
